library(devtools)
library(tidyverse)#涉及数据处理
library(fs)
library(testthat)

use_git()
use_r("replace_all_text")
use_r("sub_fasID")
use_r("read_aslist")
use_r("sort_list")
use_r("splitChr")
use_r("chooseChr")
load_all()
#test
use_mit_license("Shaoqian Ma")
document()
?splitChr
check()
?usethis::use_data()
load("E:/R.proj/Advanced_R/all_text.RData")
usethis::use_data(all_text,overwrite = T)
load("E:/R.proj/Advanced_R/tex.RData")
usethis::use_data(tex,overwrite = T)
load("E:/R.proj/Advanced_R/tex2.RData")
usethis::use_data(tex2,overwrite = F)
load("E:/R.proj/Advanced_R/tex3.RData")
usethis::use_data(tex3,overwrite = F)
load("E:/R.proj/Advanced_R/complicated_id.RData")
usethis::use_data(complicated_id,overwrite = F)
document()
check()
# system.file("extdata", "test.faa", package = "msqchr")
use_package("utils")
use_readme_rmd()
?usethis::use_build_ignore()
usethis::use_vignette("msq-vignette")
use_readme_rmd()
rmarkdown::render("README.Rmd")
devtools::build()
